### ISSUE TITLE
Cyndaquil behavior not set correctly 

### ISSUE THREAD

**Issue by JG-SWE** [kwsch/PermuteMMO#14]
![image](https://github.com/kwsch/PermuteMMO/assets/25264372/fcf668ec-3501-4e86-aba0-da8ae1f1d0d5)

Cyndaquil is set as an Oblivious pokemon, but in reality it is Skittish. I learned this because after reaching the chain in the image, they started running away and disappearing.

This affects how the tool calculates shiny permutations for this species; as it is, Cyndaquil outbreaks will not report any shiny permutations unless they are single advance chains or contain B2 steps with Quilava/Alpha spawns.

**Comment by kwsch** [comment]
Relevant commit: 
https://github.com/kwsch/PermuteMMO/commit/d1a18c6e2d39a5e7c32c1d1f811038f76caf0077
@Lusamine 

Pretty sure they're categorized as obvious because of their varied behavior sets, and oblivious being close enough to keep you from attempting impossible paths.

**Comment by JG-SWE** [comment]
In my opinion, there should be further distinction between these hybrid "flee/attack" behaviored species and Oblivious species. Based on the commit description, one should be able to perform S1, A1, A2, A3 steps as part of permutations for species with the "flee/attack" behavior.

Though I do understand the reasoning behind playing it safe and marking them as Oblivious to prevent people from attempting S2, S3, S4, A4 steps. I haven't looked at the tool's implementation, but creating permutations combining S1, A1, A2, A3 steps while excluding S2, S3, S4, A4 steps may be non-trivial.

**Comment by kwsch** [comment]
It'd need a new behavior type that would cause it to change behaviors to aggressive if another already exists, and a bunch of handling for that. 
It's problematic for the user doing the permutations because they have to keep track of which is the skittish.
I don't think it's worth the effort and future confusion, and it's good enough to just have less permutations than too-tricky. It'd probably slow down the permutations with the extra logic, so it would potentially need to be handled separately (fork)

**Comment by JG-SWE** [comment]
Given that there's only two species that fit this description, I am inclined to agree that it is likely not worth the effort. 

Thanks for addressing this!
